# Generated by Django 5.2 on 2025-06-03 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_venue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
