# Generated by Django 5.2 on 2026-09-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_verificationchallenge'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='verificationchallenge',
            name='one_open_verification_per_user',
        ),
        migrations.AddField(
            model_name='verificationchallenge',
            name='proof_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='verificationchallenge',
            name='reason',
            field=models.CharField(choices=[('signup', 'Signup'), ('email_update', 'Email update'), ('password_change', 'Password change'), ('password_recovery', 'Password recovery'), ('two_factor_login', 'Two-factor login'), ('venue_email', 'Venue email')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='verificationchallenge',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True), models.Q(('reason', 'two_factor_login'), _negated=True)), fields=('user',), name='one_open_verification_per_user'),
        ),
        migrations.AddConstraint(
            model_name='verificationchallenge',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True), ('reason', 'two_factor_login')), fields=('user',), name='one_open_login_challenge_per_user'),
        ),
    ]
