# Generated by Django 5.2 on 2025-12-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueEmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
