# Generated by Django 5.2 on 2025-12-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venueapplication',
            old_name='admin_fullname',
            new_name='admin_firstname',
        ),
        migrations.AddField(
            model_name='venueapplication',
            name='admin_lastname',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
