# Generated by Django 5.2 on 2025-11-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venueupdatemenuimage',
            name='update_request',
        ),
        migrations.AddField(
            model_name='venueimage',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venueimage',
            name='marked_for_deletion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venuemenuimage',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venuemenuimage',
            name='marked_for_deletion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='venues/'),
        ),
        migrations.DeleteModel(
            name='VenueUpdateImage',
        ),
        migrations.DeleteModel(
            name='VenueUpdateMenuImage',
        ),
    ]
