# Generated by Django 5.2 on 2026-02-18 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_remove_reservation_name_reservation_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueClosedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('note', models.CharField(blank=True, max_length=120)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_times', to='venues.venue')),
            ],
            options={
                'ordering': ['date', 'time'],
                'constraints': [models.UniqueConstraint(fields=('venue', 'date', 'time'), name='uniq_venue_date_time_closedtime')],
            },
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_closed', models.BooleanField(default=False)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('closes_next_day', models.BooleanField(default=False)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_days', to='venues.venue')),
            ],
            options={
                'ordering': ['weekday'],
                'constraints': [models.UniqueConstraint(fields=('venue', 'weekday'), name='uniq_venue_weekday_workingday')],
            },
        ),
    ]
