# Generated by Django 5.2 on 2025-11-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_remove_venueupdatemenuimage_update_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='last_name',
        ),
    ]
