# Generated by Django 5.2 on 2025-12-24 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_rename_admin_fullname_venueapplication_admin_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='image',
        ),
    ]
