# Generated by Django 5.2 on 2026-03-05 19:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_reservation_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationOutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('channel', models.CharField(choices=[('websocket', 'WebSocket'), ('email', 'Email'), ('both', 'Both')], default='both', max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='venues.reservation')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='venues.venue')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='venues_rese_status_4f1bd7_idx'), models.Index(fields=['venue', 'created_at'], name='venues_rese_venue_i_3b1b41_idx')],
            },
        ),
    ]
