# Generated by Django 5.2 on 2025-12-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venueapplication',
            name='capacity',
        ),
    ]
