# Generated by Django 5.2 on 2025-12-19 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_remove_venueapplication_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venueapplication',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='venueapplication',
            name='reviewed',
        ),
        migrations.AddField(
            model_name='venueapplication',
            name='admin_fullname',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='venueapplication',
            name='admin_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='venueapplication',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venueapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
