# Generated by Django 5.2 on 2025-07-24 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_alter_reservation_user_alter_reservation_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='capacity',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='venues.venue'),
        ),
    ]
