# Generated by Django 5.2 on 2025-07-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0009_remove_venue_capacity_alter_reservation_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='longitude',
        ),
    ]
