# Generated by Django 5.2 on 2025-07-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0014_alter_venue_latitude_alter_venue_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='arrival_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('checked_in', 'Checked-in'), ('no_show', 'No-show')], default='pending', max_length=20),
        ),
    ]
