# Generated by Django 5.2 on 2025-07-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0015_reservation_arrival_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='arrival_status',
            field=models.CharField(choices=[('uninitialized', 'Uninitialized'), ('pending', 'Pending'), ('checked_in', 'Checked-in'), ('no_show', 'No-show')], default='uninitialized', max_length=20),
        ),
    ]
