# Generated by Django 5.2 on 2025-08-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0016_alter_reservation_arrival_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='arrival_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('checked_in', 'Checked-in'), ('no_show', 'No-show')], default='pending', max_length=20),
        ),
    ]
