# Generated by Django 5.2 on 2025-08-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0017_alter_reservation_arrival_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
