# Generated by Django 5.2 on 2025-09-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0021_venueupdaterequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(default='Ioannis', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
