# Generated by Django 5.2 on 2025-10-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0022_rename_name_reservation_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-updated_at', '-created_at', 'time']},
        ),
        migrations.AddField(
            model_name='reservation',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='special_requests',
            field=models.CharField(choices=[('none', 'None'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('gluten_free', 'Gluten-free'), ('wheelchair', 'Wheelchair accessible'), ('other', 'Other')], default='none', max_length=20),
        ),
    ]
