# Generated by Django 5.2 on 2025-09-24 15:40

import django.db.models.deletion
import venues.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0022_rename_name_reservation_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-updated_at', '-created_at', 'time']},
        ),
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/venues/'),
        ),
        migrations.CreateModel(
            name='VenueUpdateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=venues.models.venue_image_upload)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='venues.venueupdaterequest')),
            ],
        ),
        migrations.CreateModel(
            name='VenueUpdateMenuImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=venues.models.menu_image_upload)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_images', to='venues.venueupdaterequest')),
            ],
        ),
    ]
