# Generated by Django 5.2 on 2025-09-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0023_alter_reservation_options_alter_venue_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venueupdateimage',
            old_name='venue',
            new_name='update_request',
        ),
        migrations.RenameField(
            model_name='venueupdatemenuimage',
            old_name='venue',
            new_name='update_request',
        ),
    ]
