# Generated by Django 5.2 on 2025-09-26 18:08

import django.db.models.deletion
import venues.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0024_rename_venue_venueupdateimage_update_request_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='venueupdaterequest',
            unique_together={('venue', 'approval_status')},
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=venues.models.venue_image_upload)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='venues.venue')),
            ],
        ),
        migrations.CreateModel(
            name='VenueMenuImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=venues.models.menu_image_upload)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_images', to='venues.venue')),
            ],
        ),
        migrations.RemoveField(
            model_name='venueupdaterequest',
            name='image',
        ),
    ]
