# Generated by Django 5.2 on 2025-09-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0025_alter_venueupdaterequest_unique_together_venueimage_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='venueupdaterequest',
            unique_together=set(),
        ),
    ]
