# Generated by Django 5.2 on 2025-10-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0023_alter_reservation_options_reservation_allergies_and_more'),
        ('venues', '0026_alter_venueupdaterequest_unique_together'),
    ]

    operations = [
    ]
