# Generated by Django 5.2 on 2025-10-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0027_merge_20251006_2048'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='venueupdaterequest',
            unique_together={('venue', 'approval_status')},
        ),
        migrations.RemoveField(
            model_name='venueupdaterequest',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='venueupdaterequest',
            name='longitude',
        ),
    ]
