# Generated by Django 5.2 on 2025-10-06 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0028_alter_venueupdaterequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='venueupdaterequest',
            unique_together=set(),
        ),
    ]
