# Generated by Django 5.2 on 2025-11-15 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0029_alter_venueupdaterequest_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='available_tables',
        ),
    ]
