# Generated by Django 5.2 on 2025-11-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0030_remove_venue_available_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venueimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='venueimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
