# Generated by Django 5.2 on 2025-11-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0031_alter_venueimage_options_venueimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueupdaterequest',
            name='removed_menu_image_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='venueupdaterequest',
            name='removed_venue_image_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
