# Generated by Django 5.2 on 2025-11-20 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0032_venueupdaterequest_removed_menu_image_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venueupdaterequest',
            name='removed_menu_image_ids',
        ),
        migrations.RemoveField(
            model_name='venueupdaterequest',
            name='removed_venue_image_ids',
        ),
    ]
