FROM python:3.12-slim

WORKDIR /app
ENV STATIC_ROOT=/app/staticfiles MEDIA_ROOT=/app/media

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    gettext \
    && rm -rf /var/lib/apt/lists/*

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend .

EXPOSE 8000

CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "openspots.asgi:application"]
