# Generated by Django 5.2 on 2025-07-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unverified_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
