# Generated by Django 5.2 on 2025-07-16 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_code_generated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='code_generated_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_code',
        ),
    ]
