# Generated by Django 5.2 on 2026-09-14 19:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_devicesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('signup', 'Signup'), ('email_update', 'Email update'), ('password_change', 'Password change'), ('password_recovery', 'Password recovery')], max_length=24)),
                ('email', models.EmailField(max_length=254)),
                ('payload', models.JSONField(default=dict)),
                ('code_hash', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('code_expires_at', models.DateTimeField()),
                ('last_sent_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('reset_token_hash', models.CharField(blank=True, max_length=64)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True)), fields=('user',), name='one_open_verification_per_user')],
            },
        ),
    ]
