# Generated by Django 5.2 on 2026-02-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_venueclosedtime_workingday'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
