# Generated by Django 5.2 on 2026-06-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0005_reservationoutboxevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="smoking",
            field=models.CharField(
                choices=[
                    ("no_preference", "No preference"),
                    ("smoking", "Smoking"),
                    ("non_smoking", "Non-smoking"),
                ],
                default="no_preference",
                max_length=20,
            ),
        ),
    ]
